# [START gae_flex_quickstart_yaml]
runtime: nodejs12
instance_class: F4_1G
env: standard

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.8
